<?php
/**
 * introduction-apache.phtml
 * 
 * For Apache web-server's configuration.
 * 
 * @version   1.0
 * @package   op-core
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright 2014 (C) Tomoaki Nagahara All right reserved.
 */

//	real path
$full_path = dirname($_SERVER['SCRIPT_FILENAME']);

//	meta path
$doc_path = dirname($_SERVER['SCRIPT_NAME']);

?>
<p class="i18n">Please check of <b>"<?php print $full_path ?>/.htaccess"</b> file's settings.</p>
<ol>
	<li><b>RewriteEngine: </b><span class="i18n">Change to <b>"ON"</b> from <span>"OFF"</span>.</span></li>
	<?php if( $doc_path !== '/' ): ?>
		<li><b>RewriteBase: </b><span  class="i18n">Change to <b>"<?php print $doc_path ?>"</b> from <span>"/"</span>.</span></li>
	<?php endif; ?>
</ol>

<!-- Include jQuery load html. -->
<?php
$version = 1;
include(OnePiece5::ConvertPath('op:/Template/jQuery-load.phtml'));
?>

<!-- Include ajax i18n. -->
<script type="text/javascript" charset="utf-8">
<?php include(OnePiece5::ConvertPath('op:/js/i18n.js')); ?>
</script>
<?php

