<?php
/* @var $this App */

//	Init unit name
if( empty($unit_name) ){
	$this->StackError("Unit name is empty. \($unit_name)\\",'en');
}
 
switch( $unit_name ){
	case '_self-test':
		$_unit_name = 'selftest';
		break;
		
	case 'credit-card':
		$_unit_name = 'creditcard';
		break;
		
	case 'language':
		$_unit_name = $unit_name;
		break;
		
	default:
	$this->StackError("Does not define this unit name. \($unit_name)\\",'en');
}


?>
<div>
	<h1><?= $this->i18n()->En('Introduction of method') ?></h1>
	<p><?= $this->i18n()->En('Please execute this command.') ?></p>
	<div style="border: 1px solid black; margin:1em; padding:1em;">
		<code>
			cd <?= $this->ConvertPath('app:/') ?><br/>
			git clone https://github.com/TomoakiNagahara/op-unit-<?= $_unit_name ?>.git <?= $unit_name ?><br/>
		</code>
	</div>
	<p>
		<?= $this->i18n()->En('Or Download here') ?> =&gt; 
		<a href="https://github.com/TomoakiNagahara/op-unit-<?= $_unit_name ?>/archive/master.zip">
			https://github.com/TomoakiNagahara/op-unit-<?= $_unit_name ?>/archive/master.zip
		</a>
	</p>
	<p>And then reload this page.</p>
</div>
<?php
